export default {
  login: "holiman",
  id: 142290,
  node_id: "MDQ6VXNlcjE0MjI5MA==",
  avatar_url: "https://avatars.githubusercontent.com/u/142290?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/holiman",
  html_url: "https://github.com/holiman",
  followers_url: "https://api.github.com/users/holiman/followers",
  following_url: "https://api.github.com/users/holiman/following{/other_user}",
  gists_url: "https://api.github.com/users/holiman/gists{/gist_id}",
  starred_url: "https://api.github.com/users/holiman/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/holiman/subscriptions",
  organizations_url: "https://api.github.com/users/holiman/orgs",
  repos_url: "https://api.github.com/users/holiman/repos",
  events_url: "https://api.github.com/users/holiman/events{/privacy}",
  received_events_url: "https://api.github.com/users/holiman/received_events",
  type: "User",
  site_admin: false,
  name: "Martin Holst Swende",
  company: null,
  blog: "martin.swende.se",
  location: "Stockholm, Sweden",
  email: null,
  hireable: true,
  bio: null,
  twitter_username: null,
  public_repos: 84,
  public_gists: 28,
  followers: 393,
  following: 2,
  created_at: "2009-10-20T19:14:18Z",
  updated_at: "2021-06-28T12:46:55Z",
};
